'\" t
.\"     Title: gcloud-compute-target-pools-create
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/20/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "GCLOUD\-COMPUTE\-TARGET\-POOLS\-CREATE" "1" "05/20/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gcloud-compute-target-pools-create \- Define a load\-balanced pool of virtual machine instances
.SH "SYNOPSIS"
.sp
\fBgcloud compute target\-pools create\fR NAME [\-\-backup\-pool BACKUP_POOL] [\-\-description DESCRIPTION] [\-\-failover\-ratio FAILOVER_RATIO] [\-\-health\-checks HEALTH_CHECK [HEALTH_CHECK \&...]] \-\-instances INSTANCE [INSTANCE \&...] [\-\-region REGION] [\-\-session\-affinity SESSION_AFFINITY; default="NONE"] [\-h, \-\-help]
.SH "DESCRIPTION"
.sp
\fBgcloud compute target\-pools create\fR is used to create a target pool\&. A target pool resource defines a group of instances that can receive incoming traffic from forwarding rules\&. When a forwarding rule directs traffic to a target pool, Google Compute Engine picks an instance from the target pool based on a hash of the source and destination IP addresses and ports\&. For more information on load balancing, see https://developers\&.google\&.com/compute/docs/load\-balancing/\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the target pool\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-backup\-pool\fR \fIBACKUP_POOL\fR
.RS 4
Together with \(lq\-\-failover\-ratio\(rq, this flag defines the fallback behavior of the target pool (primary pool) to be created by this command\&. If the ratio of the healthy instances in the primary pool is at or below the specified \(lq\-\-failover\-ratio value\(rq, then traffic arriving at the load\-balanced IP address will be directed to the backup pool\&. If this flag is provided, then \(lq\-\-failover\-ratio\(rq is required\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional description of this target pool\&.
.RE
.PP
\fB\-\-failover\-ratio\fR \fIFAILOVER_RATIO\fR
.RS 4
Together with \(lq\-\-backup\-pool\(rq, defines the fallback behavior of the target pool (primary pool) to be created by this command\&. If the ratio of the healthy instances in the primary pool is at or below this number, traffic arriving at the load\-balanced IP address will be directed to the backup pool\&. For example, if 0\&.4 is chosen as the failover ratio, then traffic will fail over to the backup pool if more than 40% of the instances become unhealthy\&. If not set, the traffic will be directed the instances in this pool in the \(lqforce\(rq mode, where traffic will be spread to the healthy instances with the best effort, or to all instances when no instance is healthy\&. If this flag is provided, then \(lq\-\-backup\-pool\(rq is required\&.
.RE
.PP
\fB\-\-health\-checks\fR \fIHEALTH_CHECK [HEALTH_CHECK \&...]\fR
.RS 4
Specifies HTTP health check resources to use to determine the health of instances in this pool\&. If no health check is specified, traffic will be sent to all instances in this target pool as if the instances were healthy, but the health status of this pool will appear as unhealthy as a warning that this target pool does not have a health check\&.
.RE
.PP
\fB\-\-instances\fR \fIINSTANCE [INSTANCE \&...]\fR
.RS 4
Specifies a list of instances that will receive traffic directed to this target pool\&. Each entry must be specified by a relative or fully\-qualified path to the instance (e\&.g\&., \(lq\-\-instances us\-central1\-a/instances/my\-instance\(rq)\&. All instances in one target pool must belong to the same region as the target pool\&. Instances do not need to exist at the time the target pool is created and can be created afterwards\&.
.RE
.PP
\fB\-\-region\fR \fIREGION\fR
.RS 4
The region in which the forwarding rule will be created\&.
.RE
.PP
\fB\-\-session\-affinity\fR \fISESSION_AFFINITY\fR
.RS 4
Specifies the session affinity option for the connection\&. If \(lqNONE\(rq is selected, then connections from the same client IP address may go to any instance in the target pool\&. If \(lqCLIENT_IP\(rq is selected, then connections from the same client IP address will go to the same instance in the target pool\&. If \(lqCLIENT_IP_PROTO\(rq is selected, then connections from the same client IP with the same IP protocol will go to the same client pool\&. If not specified, then \(lqNONE\(rq is used as a default\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
