'\" t
.\"     Title: gcloud-compute-instances-set-disk-auto-delete
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/20/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "GCLOUD\-COMPUTE\-INSTANCES\-SET\-DISK\-AUTO\-DELETE" "1" "05/20/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gcloud-compute-instances-set-disk-auto-delete \- Set auto\-delete behavior for disks
.SH "SYNOPSIS"
.sp
\fBgcloud compute instances set\-disk\-auto\-delete\fR INSTANCE [\-\-auto\-delete | \-\-no\-auto\-delete] [\-\-device\-name DEVICE_NAME | \-\-disk DISK] [\-\-zone ZONE] [\-h, \-\-help]
.SH "DESCRIPTION"
.sp
\fB$gcloud compute instances set\-disk\-auto\-delete\fR is used to configure the auto\-delete behavior for disks attached to Google Compute Engine virtual machines\&. When auto\-delete is on, the persistent disk is deleted when the instance it is attached to is deleted\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fIINSTANCE\fR
.RS 4
The name of, or a fully\- or partially\-qualified path to the instance for which to set disk auto\-deletion\&. Using a path containing the zone will render the \-\-zone flag optional\&. For example, providing \(lqus\-central2\-a/instances/my\-instance\(rq is equivalent to providing \(lqmy\-instance\(rq with \(lq\-\-zone us\-central2\-a\(rq\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-auto\-delete\fR
.RS 4
Set auto\-delete for the given disk to true\&.
.RE
.PP
\fB\-\-device\-name\fR \fIDEVICE_NAME\fR
.RS 4
Specifies a disk to set auto\-delete for by its device name, which is the name that the guest operating system sees\&. The device name is set at the time that the disk is attached to the instance, and need not be the same as the persistent disk name\&. If the disk\(cqs device name is specified, then its persistent disk name must not be specified using the \(lq\-\-disk\(rq flag\&.
.RE
.PP
\fB\-\-disk\fR \fIDISK\fR
.RS 4
Specifies a disk to set auto\-delete for by its resource name\&. If you specify a disk to set auto\-delete for by persistent disk name, then you must not specify its device name using the \(lq\-\-device\-name\(rq flag\&.
.RE
.PP
\fB\-\-no\-auto\-delete\fR
.RS 4
Set auto\-delete for the given disk to false\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the instance\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
